accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
]

smash_note/urls.py
from django.urls import path
from .import views

from django.conf.urls.static import static
from django.conf import settings
app_name="smash_note"


urlpatterns = [
    path('',views.CharacterSelect.as_view(),name='character_index'),#name=によりhtml上でcharaという名前で呼び出せる
    path('<int:pk>/',views.CharacterDetailView.as_view(),name="character_detail"),

    path('<int:pk>/create/',views.MemoCreateView.as_view(),name="memo_create"),
    #path('create/',views.MemoCreateView.as_view(),name='memo_create'),
    path('<int:pk>/update/',views.MemoUpdateView.as_view(),name='memo_update'),
    path('<int:pk>/delete/',views.MemoDeleteView.as_view(),name='memo_delete'),
    #path('<int:pk>/update/<int:pk>',views.MemoUpdateView.as_view(),name='memo_update'),
    path('favorite-characters/', views.FavoriteCharactersView.as_view(), name='favorite_characters'),
    path('<int:pk>/fcdelete/',views.FavoriteDeleteView.as_view(),name='fc_delete'),
    path('tool/', views.ToolView.as_view(), name='tool'),
    path('userate/', views.UseRateView.as_view(), name='use_rate'),
    path('winrate/', views.WinRateView.as_view(), name='win_rate'),


]

smash_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('smash_note/',include('smash_note.urls')),#smash_noteのurlだとsmash_noteに飛ぶ  そしてこれをコメントアウトしないとmigrationできない？
    path('',RedirectView.as_view(url = '/smash_note/')),#urlになにもないとsmash_noteにurlがなる
    path('accounts/',include('accounts.urls')),# accounts.urls.pyを読み込むための設定を追加
    path('social-auth/', include('allauth.urls')),
    #http://127.0.0.1:8000/social-auth/google/login/?next=/
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#画像を表示させる時に使うやつ
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

smash_note/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model#独自のユーザーモデルを使用するために

#######
User = get_user_model()#独自のUserモデルを使用

class Character(models.Model):
    #character_id = models.IntegerField#djangoがidという名前で定義してくれるので不要？
    character_name = models.CharField(max_length=255)
    image_url = models.ImageField(upload_to='static/images/')
    def __str__(self):
        return self.character_name#このクラス名で呼び出されたときにreturnのコードを実行



'''
    models.ForeignKeyの第一引数には、関連するモデルのクラス名を指定する必要があります。例えば、models.ForeignKey(Character)と書くことで、
    Characterモデルと関連付けることができます。この場合、player_character_idフィールドはCharacterのインスタンスを参照することができます。

    Characterモデルにはidという名前の自動生成されたプライマリーキーがありますが、models.ForeignKeyにCharacterを渡すことで、
    そのプライマリーキーと紐づけることができます。つまり、player_character_idは、Characterモデルのプライマリーキーであるidを
    参照することになります。↓
    '''
class MatchResult(models.Model):#djangoだとキャメルケースで書く
    player_character_id = models.ForeignKey(Character,related_name='player_character',null=True,blank=True,on_delete=models.CASCADE)
    opponent_character_id = models.ForeignKey(Character,related_name='opponent_character',on_delete=models.CASCADE)
    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    #win_flag = models.BooleanField()
    win_flag = models.BooleanField(null=True)
    memo = models.TextField(max_length=3000)
    memo_date = models.DateField(auto_now_add=True)


    def __str__(self):
        return str(self.id)
    def get_absolute_url(self):
        #return reverse("smash_note:character_detail", kwargs={"pk": self.pk})#urlからリダイレクト先のurlを調べる
        return reverse("smash_note:character_detail", kwargs={"pk": self.opponent_character_id.pk})#urlからリダイレクト  つまり呼び出したと似にopponent_character_idのurlに飛ぶ


class FavoriteCharacter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    characters = models.ManyToManyField(Character,  blank=True)

    def __str__(self):
        return self.user.username
# Userモデルの保存後にFavoriteCharacterインスタンスを作成する


@receiver(post_save, sender=User)
def create_favorite_character(sender, instance, created, **kwargs):
    if created:
        FavoriteCharacter.objects.create(user=instance)

smash_note/forms.py
#from django.db import models
from django import forms
from .models import MatchResult,Character,FavoriteCharacter
class MatchResultForm(forms.ModelForm):

    class Meta:

        model = MatchResult
        fields = ("player_character_id",'opponent_character_id',"author")


class CharacterSelectForm(forms.Form):
    character = forms.ModelChoiceField(queryset=Character.objects.all())
class FavoriteCharacterForm(forms.ModelForm):
    class Meta:
        model = FavoriteCharacter
        fields = ['characters']

smash_note/views.py
from django.urls import reverse_lazy

#from django.views.generic.edit import CreateView
from .models import Character,MatchResult,FavoriteCharacter
from .forms import MatchResultForm, CharacterSelectForm,FavoriteCharacterForm
from django.shortcuts import get_object_or_404 # get_object_or_404をインポート
from django.contrib.auth.mixins import LoginRequiredMixin#アクセス制御
from django.core.exceptions import PermissionDenied#Updateで使う

from django.shortcuts import render,redirect
from django.http import HttpResponse



from django.contrib.auth.mixins import LoginRequiredMixin#アクセス制御


from django.views import View,generic


from django.db.models import Count,Sum

import math

class CharacterSelect(generic.ListView):
    model = Character#表示させるなら横６スマホ？pc１０？
    ordering = ['id']#idを小さい順にソート
class CharacterDetailView(generic.DetailView):
    """_summary_

    効果:
        - このキャラに対する勝利数、勝率を表示
        - このキャラに対する投稿を表示
        - お気に入りキャラで投稿をフィルター
        - （予定）お気に入りキャラごとに勝率を表示
    """
    model = Character#テンプレート名を省略しているので、Character_detail.htmlが対応される

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        character = self.object
        #authorが現在のログインユーザーであるオブジェクトのみをフィルタリングしています
        match_results =  MatchResult.objects.filter(author=self.request.user)
        match_results = match_results.filter(opponent_character_id=character.id)#opponent_character_idで絞り込み
        filter_id = self.request.GET.get('filter')#自分のキャラのid
        win_flag = self.request.GET.get('win_rose')#勝ちか負けどちらでフィルターするか


        if filter_id:
            match_results = match_results.filter(player_character_id=filter_id)
        if win_flag == "True":
            print('t')
            match_results = match_results.filter(win_flag=True)
        elif win_flag=='False':
            print('f')
            match_results = match_results.filter(win_flag=False)

        context['match_results'] = match_results

        if filter_id:
            filtered_character = Character.objects.get(id=filter_id)
        else:
            filtered_character = None
        context['filter_character'] = filtered_character

        wins = match_results.filter(opponent_character_id=character, win_flag=True).count()
        losses = match_results.filter(opponent_character_id=character, win_flag=False).count()
        total_matches = match_results.count()
        nocon = total_matches-wins-losses#無効試合

        if( (wins+losses) ==0):
            win_rate = '?'#勝ちも負けも記録されていないとき勝率を？にする
        elif(wins == 0 ):
            win_rate=0#0除算回避
        else:
            win_rate = round(wins / (wins+losses) * 100) #if (wins+losses) != 0 else 0
        context['wins'] = wins
        context['losses'] = losses
        context['total_matches'] = total_matches
        context['valid_total_matches'] = wins+losses
        context['win_rate'] = win_rate
        context['nocon']=nocon


        character = Character.objects.order_by('id')
        context['characters'] = character

        if self.request.user.is_authenticated:
            try:
                favorite_characters = FavoriteCharacter.objects.get(user=self.request.user)
                context['favorite_characters'] = favorite_characters.characters.all()
            except FavoriteCharacter.DoesNotExist:
                pass
        return context

def filter_view(request):

    filter_id = request.GET.get('filter')
    if filter_id:
        filtered_character = Character.objects.get(id=filter_id)
        filtered_models = MatchResult.objects.filter(player_character_id=filter_id)
    else:
        filtered_models = MatchResult.objects.all()
        filtered_character = None
    context = {'models': filtered_models, 'filter_character': filtered_character}
    return render(request, 'smash_note/character_detail.html', context)




class MemoCreateView(generic.CreateView): # MemoCreateViewを定義し、CreateViewを継承する
    model = MatchResult # モデルにMatchResultを指定
    fields = ['player_character_id','win_flag', 'memo'] # フォームのフィールドにwin_flagとmemoを指定
    template_name = 'smash_note/MatchResult_form.html' # テンプレートの名前を指定

    def form_valid(self, form): # フォームが妥当かどうかを検証するためのメソッド
        form.instance.author = self.request.user # ログインユーザーをauthorに追加

        form.instance.opponent_character_id = get_object_or_404(Character, pk=self.kwargs['pk']) # urlのpkからキャラクターを取得し、opponent_character_idに追加
        # player_character_idが指定されていない場合はnullをセット

        return super().form_valid(form) # 親クラスのメソッドを呼び出し、返り値を返す

    def get_context_data(self, **kwargs):
        context = {}
        favorite_characters = FavoriteCharacter.objects.get(user=self.request.user.id)#ログインユーザーのお気に入りキャラを取得
        context['favorite_characters'] = favorite_characters.characters.all()
        return context

class MemoUpdateView(LoginRequiredMixin,generic.UpdateView):
    model = MatchResult

    fields=  ['player_character_id','win_flag','memo']

    def dispatch(self,request,*args,**kwargs):#dispatchメソッドをオーバーライド
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied("You do not have permission to edit.")
        return super(MemoUpdateView,self).dispatch(request,*args,**kwargs)

class MemoDeleteView(generic.DeleteView):
    model = MatchResult
    template_name = 'smash_note/matchresult_confirm_delete.html'
    #success_url = reverse_lazy('smash_note:character_index')
    #success_url = reverse_lazy('smash_note:character_detail')
    def get_success_url(self):
        #return reverse_lazy('smash_note:character_detail', kwargs={'pk': self.object.pk})

        return reverse_lazy('smash_note:character_detail', kwargs={'pk': self.object.opponent_character_id.pk})




def get_character_stats(character):#勝率計算
    matches_as_opponent = MatchResult.objects.filter(opponent_character_id=character.id)
    total_matches = matches_as_opponent.count() + MatchResult.objects.filter(player_character_id=character.id).count()
    wins_as_player = MatchResult.objects.filter(player_character_id=character, win_flag=True).count()
    win_rate = wins_as_player / total_matches * 100 if total_matches > 0 else 0
    stats = {'total_matches': total_matches, 'wins': wins_as_player, 'win_rate': win_rate}
    #return stats
    print("ai")
    return HttpResponse(matches_as_opponent)



class FavoriteCharactersView(View):
    """
    - お気に入りのキャラを追加、削除
    """
    def get(self, request):
        form = FavoriteCharacterForm()
        character_choices = Character.objects.all
        favorite_character = request.user.favoritecharacter


        if self.request.user.is_authenticated:
            try:
                favorite_characters = FavoriteCharacter.objects.get(user=self.request.user)
                favorite_characters = favorite_characters.characters.all()

                return render(request, 'smash_note/favorite_characters.html', {'form': form, 'character_choices': character_choices,'favorite_character':favorite_character,'favorite_characters':favorite_characters})
            except FavoriteCharacter.DoesNotExist:
                pass
        return render(request, 'smash_note/favorite_characters.html', {'form': form, 'character_choices': character_choices,'favorite_character':favorite_character})

    def post(self, request):
        form = FavoriteCharacterForm(request.POST)
        character_choices = Character.objects.all
        if form.is_valid():
            character_id = form.cleaned_data['characters']
            selected_chara_id = request.POST.get('characters')

            favorite_character = request.user.favoritecharacter
            favorite_character.characters.add(selected_chara_id)

            #return redirect('smash_note/character_list.html')
            #return reverse_lazy("smash_note:favorite_character")

        try:
            favorite_characters = FavoriteCharacter.objects.get(user=self.request.user)
            favorite_characters = favorite_characters.characters.all()
            return render(request, 'smash_note/favorite_characters.html', {'form': form, 'character_choices': character_choices,'favorite_character':favorite_character,'favorite_characters':favorite_characters})
        except FavoriteCharacter.DoesNotExist:
            pass
        return render(request, 'smash_note/favorite_characters.html', {'form': form,'character_choices': character_choices,'favorite_character':favorite_character})

class FavoriteDeleteView(View):
    print("a")
    #template_name = 'smash_note/matchresult_confirm_delete.html'
    def get(self, request,pk):
        favorite_character = get_object_or_404(FavoriteCharacter, user=request.user)
        pk=self.kwargs['pk']
        favorite_character.characters.remove(pk)
        favorite_character.save()
        return redirect('smash_note:favorite_characters')



class ToolView(generic.ListView):#使用率、勝率の高い低いで3キャラ表示
    template_name = 'smash_note/tool.html'
    model = MatchResult
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        match_results =  MatchResult.objects.filter(author=self.request.user)#ログインユーザーの試合結果のみに絞り込んでいる

        chara_num  = Character.objects.count()#現在登録されているキャラクター数
        player_wins = match_results.filter(win_flag=True).values('opponent_character_id').annotate(win_count=Count('opponent_character_id'))
        '''
        ↑match_results テーブルの中で win_flag=True のレコードを取得し、player_character_id ごとにグループ化して、各 player_character_id の出現回数を win_count として集計しています。結果は、player_character_id と win_count のペアを持つ辞書の形式で返されます。
        '''
        player_losses = match_results.filter(win_flag=False).values('opponent_character_id').annotate(loss_count=Count('opponent_character_id'))


        player_wins = {item['opponent_character_id']: item['win_count'] for item in player_wins}
        player_losses = {item['opponent_character_id']: item['loss_count'] for item in player_losses}
        '''

smash_note/templates/smash_note/MatchResult_form.html
{% extends './base.html' %}
{%load static%}

{%block ex_head%}
    <link rel="stylesheet" href="{% static 'css/radio_button.css'%}">
    <script src="{% static 'js/radioButton.js'%}"></script>
{% endblock %}
{% block content %}

<div class="container text-center">
        <h1>{{object|yesno:'更新,対戦結果を記録'}}</h1>
        {%comment%}
        object は、UpdateView や CreateView で使用される model で指定されたモデルのオブジェクトを表します。yesno フィルターは、条件式が真である場合には第1引数の文字列、偽である場合には第2引数の文字列を表示するフィルターです。

        今回の例では、テンプレート内でオブジェクトが存在する場合（つまり更新する場合）は "更新"、存在しない
        場合（つまり新規作成する場合）は "作成" を表示するようになっている
        {%endcomment%}

        <form method='post'>
            {% csrf_token %}{#おまじない#}
            {% if object  %}
                {{form.as_p}}{#編集の時#}
            {% else %}

                <div class="form-group">
                    <p><label for="id_player_character_id">あなたの使用キャラ（お気に入り）</label></p>

                    <div class="radio-tile-group">
                        {% for favorite_character in favorite_characters %}{#お気に入りキャラ#}
                          <div class="input-container">
                              <input type="radio" name="player_character_id" value="{{ favorite_character.id }}" id="{{favorite_character.id}}" onclick="doubleSelect(this)"/>
                              <div class="radio-tile">
                                <label for="{{favorite_character.id}}">
                                  <span class="c-img"><img
                                    src="{% static 'images/' %}{{ favorite_character.image_url }}" alt="{{ favorite_character.character_name }}の画像"
                                  ></span>
                                </label>
                              </div>
                          </div>
                        {% endfor %}

                      </div>{#radio-tile-group#}
                    <p> <textarea name="memo" cols="80" rows="10" maxlength="3000" required="" id="id_memo" class="mt-3"></textarea></p>
                    <p>
                        <label for="id_win_flag">勝敗:</label>
                        <select name="win_flag" id="id_win_flag">
                            <option value="unknown" selected="">不明</option>
                            <option value="true">勝ち</option>
                            <option value="false">負け</option>
                        </select>
                    </p>
                </div>
            {% endif %}



            <button type='submit' class='btn btn-primary'> {{object|yesno:'更新,作成'}} </button>
        </form>


        <div style="display: flex; justify-content: space-between;max-width:300px; margin-top: 20px;">
            <a href='JavaScript:history.back()'>
                <i class="fa-solid fa-arrow-left"></i>戻る
            </a>
            {% if object|yesno:"yes,no" == "yes" %}{#編集のときにtrue#}
                <a href="{% url 'smash_note:memo_delete' matchresult.pk %}">
                    <button type='submit' class='btn btn-danger'><i class="fa-solid fa-trash"></i></button>
                <a/>
            {% endif %}
        </div>
    </div>



{%endblock%}

smash_note/templates/smash_note/character_detail.html
{% extends './base.html' %}
{%load static%}
{%block ex_head%}
<link rel="stylesheet" href="{% static 'css/radio_button.css'%}">
{% endblock %}
{% block content %}


<div class="container text-center">
  <h1>
    VS &nbsp<span class="ml-10"><img  src="{%static 'images/'%}{{ character.image_url }}" alt="{{ character.character_name }}の画像"></span>
  </h1>

  {% if filter_character %}{#キャラでフィルターしている場合画像を表示#}
    <h1>
      You &nbsp<span class="ml-10"><img  src="{%static 'images/'%}{{ filter_character.image_url }}" alt="{{ filter_character.character_name }}の画像"></span>
    </h1>
  {% endif %}


  <h4>
    <span class="badge bg-secondary">
      勝率:  {{ win_rate }}%
    </span>
    <small>
    有効試合数: {{ valid_total_matches }}</small>
  </h4>
  <a href="{% url 'smash_note:memo_create' character.pk %}" class="btn btn-success mb-3">
    対戦を記録&nbsp;<i class="fa-solid fa-pen-to-square"></i>
  </a>



<br>
</div>

<script>
  /*選択済みのラジオボタンを押した際に、選択を解除する*/
  let beforeRadioButton = {};//これにラジオボタンのnameと前回のIDがセットで入る

  function doubleSelect(button){
    let nowRadioId = button.id;//現在のラジオボタンのidを取得
    let nowRadioName = button.name;//現在のラジオボタンのnameを取得

    if(! beforeRadioButton[nowRadioName]){//jsonに元からないと初期化
      beforeRadioButton[nowRadioName] = -1;
    }
    if(beforeRadioButton[nowRadioName] == nowRadioId){
      button.checked = false;
      beforeRadioButton[nowRadioName] = -1;
    }else{
      beforeRadioButton[nowRadioName] =nowRadioId;
    }
  }
</script>
{###ラジオボタンでフィルター###}
  <div class="form-container">
    <form method="GET" action="{% url 'smash_note:character_detail' character.id %}">
      {% load static %}
      <div class="radio-tile-group">
        {% for favorite_character in favorite_characters %}{#お気に入りキャラ#}
          <div class="input-container">
              <input type="radio" name="filter" value="{{ favorite_character.id }}" id="{{favorite_character.id}}"onclick="doubleSelect(this)"/>
              <div class="radio-tile">
                <label for="{{favorite_character.id}} ">
                  <span class="c-img"><img
                    src="{%static 'images/'%}{{ favorite_character.image_url }}" alt="{{ favorite_character.character_name }}の画像"
                  ></span>
                </label>
                
              </div>
          </div>
        {% endfor %}



      </div>{#radio-tile-group#}

      <div class="radio-tile-group">

        <div class="input-container">
          <input type="radio"name="win_rose" value="True" id='1'onclick="doubleSelect(this)">
          <div class="radio-tile">
            <label for="none"> <span class="c-text">  勝ちのみ</span></label>
          </div>
        </div>
        <div class="input-container">
          <input type="radio"name="win_rose" value="False" id='2'onclick="doubleSelect(this)">
          <div class="radio-tile">
            <label for="none"> <span class="c-text">  負けのみ</span></label>
          </div>
        </div>

      </div>


        <div class="container text-center">
          <button type="submit" class="btn btn-primary mb-3">
            フィルター<i class="fa-solid fa-filter"></i>
          </button>
        </div>

    </form>
  </div>


{% comment %}すべてのリザルトを表示  {% endcomment %}
<div style="background-color:#f3f6f9;"class=" justify-content-center align-items-center" >
  <br>
  {% if not match_results %}{#対戦記録がない場合そのことを表示#}
  <div class="col-sm-10 col-lg-3 mx-auto text-center mb-4">
    <div class="card">
      <div class="card-body">
        記録なし
      </div>
    </div>
  </div>
  <br>
  {% endif %}

  {% for result in match_results %}
    <div class="row">
      <div class="col-sm-10 col-lg-3 mx-auto mb-4">
        <div class="card">
          <div class="card-body">

            <h5 class="card-title">
              {% if result.win_flag == True%}
                勝ち
              {% elif result.win_flag == False%}
                負け
              {% else %}
                無記入
              {% endif %}
              {{result.player_character_id}}
            </h5>

            <h6 class="card-subtitle text-body-secondary mb-2">
              {{result.memo_date}}
              <a href="{% url "smash_note:memo_update" result.pk %}">編集</a>
            </h6>

            <p class="card-text">
              {{ result.memo }}
            </p>

          </div>
        </div>
      </div>
    </div>
  {% endfor %}
</div>





{%endblock%}

smash_note/templates/smash_note/favorite_characters.html
{% extends './base.html' %}
{% block content %}
<div class="container text-center align-items-center">
{% if favorite_characters %}
  <h3>あなたが登録しているお気に入り</h3>
{% else %}
  <p>お気に入りキャラがいません。</p>
{% endif %}
{% load static %}
{% for i in favorite_characters %}
  <p>
    <img src="{% static 'images/' %}{{ i.image_url }}" alt="{{ i.character_name }}の画像"></img>
    <a href="{% url 'smash_note:fc_delete' i.pk %}"><button type='submit' class='btn btn-danger'><i class="fa-solid fa-trash"></i></button></a>
  </p>
{% endfor %}

<div class="container">
  {#リストボックス（非表示）#}
  <form method="POST" action="{% url 'smash_note:favorite_characters' %}"id="favorite-form">
    <div class="form-group">
      {% csrf_token %}
      <select  name="characters" id="characters_id" style="display:none;">{#jsで値を操作するリストボックス、ユーザーは直接操作しない#}
        {% for character in character_choices %}
          <option value="{{ character.id }}">{{ character.character_name }}</option>
        {% endfor %}
      </select>
    </div>
  </form>

  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    お気に入りキャラクターを追加
  </button>
</div>




<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <div id="character-list">
          {% for character in character_choices %}
            <img src="{% static 'images/' %}{{ character.image_url }}" alt="{{ character.character_name }}" class="character-image" data-character-id="{{ character.id }}"style='height:55px; width:90px;'>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>



<script>
(()=>{
  //画像をクリックしたら、そのキャラをリストボックスで選択して送信
  document.addEventListener('DOMContentLoaded', function() {
    let form = document.getElementById('favorite-form');
    let characterIdInput = document.getElementById('characters_id');
    let characterImages = document.querySelectorAll('.character-image');

    characterImages.forEach(function(image) {
      image.addEventListener('click', function() {
        let characterId = image.getAttribute('data-character-id');
        characterIdInput.value = characterId;
        form.value =characterId;
        form.submit();
      });
    });
  });
})();
</script>


{%endblock%}

smash_note/templates/smash_note/matchresult_confirm_delete.html
{% extends './base.html' %}
{% block content %}
    <h1>memoの削除</h1>
    <p>このmemoを削除しますか？</p>
    <form method="post">
        {% csrf_token %}

        <button type='submit' class='submit delete'>削除する</button>

    </form>
    <div>
        <a href="JavaScript:history.back()">&lt; 戻る</a>
    </div>


{% endblock %}

smash_note/templates/smash_note/tool.html
{% extends './base.html' %}
{% block content %}
{% load static %}
<style>
  .list-container{
    display: flex;
    align-items: center;
    flex-direction: column
  }
</style>
<div class="container text-center align-items-center">


  <div class="row">
    <div class="col-lg-4 col-xs-12">
      <h3>あなたの使用率</h3>
        <p>1st <img src="{% static 'images/' %}{{ first_chara.image_url }}" alt="{{ first_chara.character_name }}の画像">  {{first_num|floatformat:"-1"}}%</p>
        <p>2nd <img src="{% static 'images/' %}{{ second_chara.image_url }}" alt="{{ second_chara.character_name }}の画像">  {{second_num |floatformat:"-1"}}%</p>
        <p>3rd <img src="{% static 'images/' %}{{ third_chara.image_url }}" alt="{{ third_chara.character_name }}の画像">  {{third_num|floatformat:"-1" }}%</p>
        <a href="{% url 'smash_note:use_rate'  %}"><button type='submit' class='btn btn-primary'>
          view all <i class="fa-solid fa-list-ul pl-1"></i>
        </button></a>

    </div>
    <div class="col-lg-4 col-xs-12">
      <h3>あなたが有利なキャラ</h3>
      <p>勝率</p>
      <div class="list-container">
        <ol>
          {% for item in top_3_winning %}
            {% with character=item.0  winning_rate=item.1 %}
              {% comment %} <li>{{ character_name }}: {{ winning_rate }}%</li> {% endcomment %}
              <li><img src="{% static 'images/' %}{{ character.image_url }}" alt="{{ character.character_name }}の画像">  {{ winning_rate |floatformat:"-1"}}%</li>
            {% endwith %}
          {% endfor %}
        </ol>
      </div>
      <a href="{% url 'smash_note:win_rate'  %}"><button type='submit' class='btn btn-primary'>
        view all <i class="fa-solid fa-list-ul pl-1"></i>
      </button></a>
    </div>
    <div class="col-lg-4 col-xs-12">
      <h3>あなたが不利なキャラ</h3>
      <p>勝率</p>
      <div class="list-container">
        <ol>
          {% for item in top_3_losing %}
            {% with character=item.0  losing_rate=item.1 %}
              {% comment %} <li>{{ character_name }}: {{ losing_rate }}%</li> {% endcomment %}
              <li><img src="{% static 'images/' %}{{ character.image_url }}" alt="{{ character.character_name }}の画像">  {{ losing_rate |floatformat:"-1"}}%</li>
            {% endwith %}
          {% endfor %}
        </ol>
      </div>
    </div>
  </div>





</div>
{%endblock%}