accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
]

smash_note/urls.py
from django.urls import path
from .import views

from django.conf.urls.static import static
from django.conf import settings
app_name="smash_note"


urlpatterns = [
    path('',views.CharacterSelect.as_view(),name='character_index'),#name=によりhtml上でcharaという名前で呼び出せる
    path('<int:pk>/',views.CharacterDetailView.as_view(),name="character_detail"),

    path('<int:pk>/create/',views.MemoCreateView.as_view(),name="memo_create"),
    #path('create/',views.MemoCreateView.as_view(),name='memo_create'),
    path('<int:pk>/update/',views.MemoUpdateView.as_view(),name='memo_update'),
    path('<int:pk>/delete/',views.MemoDeleteView.as_view(),name='memo_delete'),
    #path('<int:pk>/update/<int:pk>',views.MemoUpdateView.as_view(),name='memo_update'),
    path('favorite-characters/', views.FavoriteCharactersView.as_view(), name='favorite_characters'),
    path('<int:pk>/fcdelete/',views.FavoriteDeleteView.as_view(),name='fc_delete'),
    path('tool/', views.ToolView.as_view(), name='tool'),
    path('userate/', views.UseRateView.as_view(), name='use_rate'),
    path('winrate/', views.WinRateView.as_view(), name='win_rate'),


]

smash_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('smash_note/',include('smash_note.urls')),#smash_noteのurlだとsmash_noteに飛ぶ  そしてこれをコメントアウトしないとmigrationできない？
    path('',RedirectView.as_view(url = '/smash_note/')),#urlになにもないとsmash_noteにurlがなる
    path('accounts/',include('accounts.urls')),# accounts.urls.pyを読み込むための設定を追加
    path('social-auth/', include('allauth.urls')),
    #http://127.0.0.1:8000/social-auth/google/login/?next=/
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#画像を表示させる時に使うやつ
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/index.html
{% extends 'layout.html' %}

{% block title %}
{% if user.is_authenticated %}
<div class="h1">MyPage</div>
{% else %}
<div class="h1">Main</div>
{% endif %}
{% endblock %}

{% block content %}
  {# http://127.0.0.1:8000/accounts/ #}
  {% if user.is_authenticated %}{#ログインしている#}
    <div class="h2">Welcome {{ user.first_name }} {{ user.last_name }}</div>
  {% else %}
    <div>
      manage.py/templates/index.html
    </div>
    <a href="{% url 'accounts:login' %}" class="btn btn-primary">login</a>
    {% comment %} <a href="{% provider_login_url 'google'%}?next=/" class="btn btn-primary">Login with Google</a> {% endcomment %}

  {% endif %}
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        {% comment %} <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' > {% endcomment %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        {#↑bootstrapをダウンロードしなくても使える#}
        <script src="https://kit.fontawesome.com/97513716b3.js" crossorigin="anonymous"></script>
        {# ↑fontawsomeをダウンロードしなくても使える #}
        <style>body {padding-top: 80px;}</style>
        <title>smash_note</title>

    </head>
    <body>
        <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "smash_note:character_index" %}'>CharacterList</a>
            <a class = 'navbar-brand' href="{%url  'smash_note:favorite_characters'%}">お気に入り</a>
            <a class = 'navbar-brand' href="{%url  'smash_note:tool'%}">tool</a>


        </nav>
        <div class='container'>{#divはコンテナクラスをいい感じにする#}
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>